export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const FILTER_BY_GENRE = "FILTER_BY_GENRE";
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN";
export const ORDER = "ORDER";
export const GET_NAME_VIDEOGAMES = "GET_NAME_VIDEOGAMES";
export const GET_GENRE = "GET_GENRE";
export const POST_VIDEOGAME = "POST_VIDEOGAME";
export const GET_DETAIL = "GET_DETAIL";
